### ISSUE TITLE
Really

### ISSUE THREAD

**Issue by doob187** [Dope-Alpha/Plexguide-Scripts#1]
https://github.com/aelfa/scripts/blob/a0da5bdf5b6a66fb1610503fff349b20aaf3591a/mergerfs-rclone-update.sh#L1

That's really a shame 

You remove the original coder

**Comment by aelfa** [comment]
I did not. I always include original coders. That is if they have included it in their scripts. This was a copy paste of your script and I didn't change I single thing on it. Also, the scripts are mostly for my personal use.
